FROM arm32v7/debian:buster-slim

RUN apt-get update && apt-get install -y \
    --no-install-recommends --no-install-suggests \
    time \
    build-essential \
    zlib1g-dev \
    liblzo2-dev \
    liblzma-dev \
    libpng-dev \
    libfreetype6-dev \
    libfontconfig1-dev \
    libicu-dev \
    libsdl2-dev \
    && apt-get clean && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

COPY build.sh /

CMD "/build.sh"